spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PhoneShop?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-pool-size: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        connection:
          isolation: TRANSACTION_READ_COMMITTED
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher




# Add this to see detailed Hikari connection pool logging